package Ejercicio2;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

public class HiloBolita extends javax.swing.JPanel implements Runnable, ActionListener {

	private Thread thread;
	private int x;
	private final int y;
	private final int desplazamiento;
	private final Graphics g;
	private final Color color;
	private final double ancho;
	private Button b1;
	private boolean parar;
	private boolean pararBola1 = false;
	List<Thread> threads = new ArrayList<>();
	boolean isAvailable = true;

	public HiloBolita(int x, int y, int desplazamiento, Graphics g,
					  Color color, double ancho) {
		this.x = x;
		this.y = y;
		this.desplazamiento = desplazamiento;
		this.g = g;
		this.color = color;
		this.ancho = ancho;
		initComponents();

	}

	@Override

	public void run() {

		parar = false;
		Thread hiloActual = Thread.currentThread();

		while (hiloActual.getThreadGroup().getName().equals("Bolitas") && !parar) {
			synchronized (hiloActual) {

				if (!hiloActual.getName().equalsIgnoreCase("Bola 1") || !pararBola1) {
					this.isAvailable = true;
					repaint(new Rectangle(this.getX(), this.getY(), this.getWidth(), this.getHeight()));
					if (x + ancho > getWidth()) {
						do {
							x = x - desplazamiento;
							try {
								repaint(new Rectangle(this.getX(), this.getY(), this.getWidth(), this.getHeight()));
								Thread.sleep(10);
							} catch (InterruptedException e) {
								e.printStackTrace();
							}
							repaint(new Rectangle(this.getX(), this.getY(), this.getWidth(), this.getHeight()));
						} while (x > 0);
					} else {

						x = x + desplazamiento;
					}
					try {
						Thread.sleep(10);
					} catch (InterruptedException ex) {

					}
				}
			}
		}

	}

	public synchronized void notAvailable() throws InterruptedException {
		this.isAvailable = false;
	}

	public synchronized void available() {
		this.isAvailable = true;
	}

	public void paintComponent(Graphics g) {
		super.paintComponent(g);

		g.setColor(color);
		g.fillOval(x, y, 10, 10);
		g.drawOval(x, y, 10, 10);

	}

	@Override
	public void actionPerformed(ActionEvent e) {

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		pararBola = new javax.swing.JButton();

		pararBola.setText("Parar Bola 1");
		pararBola.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				pararBolaActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					  .addGroup(layout.createSequentialGroup()
									  .addGap(161, 161, 161)
									  .addComponent(pararBola)
									  .addContainerGap(148, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
																				  .addContainerGap(222, Short.MAX_VALUE)
																				  .addComponent(pararBola)
																				  .addGap(55, 55, 55))
		);
	}// </editor-fold>

	private void pararBolaActionPerformed(java.awt.event.ActionEvent evt) {
		if (this.pararBola.getText().equalsIgnoreCase("Parar Bola 1")) {
			this.pararBola1 = true;
			this.pararBola.setText("Reanudar Bola 1");
			repaint();
			try {
				Thread.sleep(100);
			} catch (InterruptedException ex) {
				Logger.getLogger(HiloBolita.class.getName()).log(Level.SEVERE, null, ex);
			}
		} else {
			this.pararBola1 = false;
			this.pararBola.setText("Parar Bola 1");
			repaint();
		}

	}

	// Variables declaration - do not modify
	private javax.swing.JButton pararBola;
	// End of variables declaration

}