package Ejercicio2v1;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class HiloBolita extends javax.swing.JPanel implements Runnable, ActionListener {

	private int x;
	private final int y;
	private int desplazamiento;
	private final Graphics g;
	private final Color color;
	private final double ancho;
	private boolean parar;
	private boolean pararBola1 = false;
	boolean isAvailable = true;

	public HiloBolita(int x, int y, int desplazamiento, Graphics g,
					  Color color, double ancho) {
		this.x = x;
		this.y = y;
		this.desplazamiento = desplazamiento;
		this.g = g;
		this.color = color;
		this.ancho = ancho;
		initComponents();

	}

	@Override

	public void run() {

		parar = false;

		for (int i = 0; i < 3500; i++) {
			paint(g, color, x, y, desplazamiento);
			mueveBolita();
			try {
				Thread.sleep(10);
			} catch (InterruptedException ex) {

			}
		}

	}

	public void paint(Graphics g, Color color, int x, int y, int desplazamiento) {

		//g.setColor(getBackground());
//		g.fillOval(x - desplazamiento, y, 50, 50);
		g.setColor(color);
		g.fillOval(x, y, (int) ancho, (int) ancho);
	}

	@Override
	public void actionPerformed(ActionEvent e) {

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		pararBola = new javax.swing.JButton();

		pararBola.setText("Parar Bola 1");
		pararBola.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				pararBolaActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					  .addGroup(layout.createSequentialGroup()
									  .addGap(161, 161, 161)
									  .addComponent(pararBola)
									  .addContainerGap(148, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
																				  .addContainerGap(222, Short.MAX_VALUE)
																				  .addComponent(pararBola)
																				  .addGap(55, 55, 55))
		);
	}// </editor-fold>

	private void pararBolaActionPerformed(java.awt.event.ActionEvent evt) {
		if (this.pararBola.getText().equalsIgnoreCase("Parar Bola 1")) {
			this.pararBola1 = true;
			this.pararBola.setText("Reanudar Bola 1");
			System.out.println("Parando Bola 1");
			repaint();
			try {
				Thread.sleep(100);
			} catch (InterruptedException ex) {
				//Logger.getLogger(HiloBolita.class.getName()).log(Level.SEVERE, null, ex);
			}
		} else {
			this.pararBola1 = false;
			this.pararBola.setText("Parar Bola 1");
			System.out.println("Reanudando bola 1");
			repaint();
		}

	}

	private javax.swing.JButton pararBola;

	public void mueveBolita() {

		if (x > getWidth()) {
			x = (int) ancho;
			desplazamiento = -desplazamiento;
		}

		if (x < 0) {
			x = 0;
			desplazamiento = -desplazamiento;
		}
		x = x + desplazamiento;

	}

}