package Ejercicio2v1;

import java.awt.*;

public class HiloBolita extends javax.swing.JPanel implements Runnable {

	private int x;
	private final int y;
	private int desplazamiento;
	private final Graphics g;
	private final Color color;
	private final double ancho;
	private boolean parar;
	public static final int BALL_SIZE = 10;

	public HiloBolita(int x, int y, int desplazamiento, Graphics g,
					  Color color, double ancho) {
		this.x = x;
		this.y = y;
		this.desplazamiento = desplazamiento;
		this.g = g;
		this.color = color;
		this.ancho = ancho;
		initComponents();

	}

	@Override
	public void run() {

		parar = false;

		for (int i = 0; i < 3500; i++) {
			estaParada();
			paint(g);
			mueveBolita();
			try {
				Thread.sleep(10);
			} catch (InterruptedException ignored) {
			}
		}

	}

	@Override
	public void paint(Graphics g) {
		super.paint(g);
		g.setColor(color);
		g.fillOval(x, y, BALL_SIZE, BALL_SIZE);
	}

	public synchronized void parar() {
		parar = true;
	}

	public synchronized void reanudar() {
		parar = false;
		notifyAll();
	}

	public synchronized void estaParada() {
		while (parar) {
			try {
				wait();
			} catch (InterruptedException ignored) {
			}
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		pararBola = new javax.swing.JButton();

		pararBola.setText("Parar Bola 1");
		pararBola.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				pararBolaActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					  .addGroup(layout.createSequentialGroup()
									  .addGap(161, 161, 161)
									  .addComponent(pararBola)
									  .addContainerGap(148, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
																				  .addContainerGap(300, Short.MAX_VALUE)
																				  .addComponent(pararBola)
																				  .addGap(55, 55, 55))
		);
	}// </editor-fold>

	private void pararBolaActionPerformed(java.awt.event.ActionEvent evt) {
		if (this.pararBola.getText().equalsIgnoreCase("Parar Bola 1")) {
			parar();
			this.pararBola.setText("Reanudar Bola 1");
			System.out.println("Parando Bola 1");

		} else {
			reanudar();
			this.pararBola.setText("Parar Bola 1");
			System.out.println("Reanudando bola 1");
		}
		paint(this.getGraphics());

	}



	private javax.swing.JButton pararBola;

	public void mueveBolita() {

		if (x > ancho) {
			x = (int) ancho;
			desplazamiento = -desplazamiento;
		}

		if (x < 0) {
			x = 0;
			desplazamiento = -desplazamiento;
		}
		x = x + desplazamiento;

	}
}